# Generated by Django 3.2.15 on 2023-03-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(verbose_name="Чашки кофе"),
        ),
    ]
