# Generated by Django 3.2.15 on 2023-03-01 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_auto_20230301_1635"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
    ]
