# Generated by Django 3.2.15 on 2023-03-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_auto_20230301_1952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="items",
        ),
        migrations.AddField(
            model_name="item",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                to="catalog.Image",
                verbose_name="Изображения",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="catalog/",
                verbose_name="Изображения",
            ),
        ),
    ]
