# Generated by Django 3.2.15 on 2023-03-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_auto_20230301_2031"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.AddField(
            model_name="image",
            name="item",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
                verbose_name="Товар",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Будет приведено к ширине 1280px",
                null=True,
                upload_to="uploads",
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                default=None,
                help_text="Будет приведено к ширине 1280px",
                null=True,
                upload_to="catalog",
                verbose_name="Изображение",
            ),
        ),
    ]
