# Generated by Django 3.2.15 on 2023-03-08 09:12

import catalog.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_auto_20230302_1431"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("weight", "id"),
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={
                "default_related_name": "images",
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "default_related_name": "items",
                "ordering": ("name",),
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "default_related_name": "tags",
                "ordering": ("slug",),
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="items",
                to="catalog.Tag",
                verbose_name="Тэги",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                default="Описание товара",
                help_text="Описание должно содержать слова 'превосходно, роскошно'",
                validators=[catalog.models.custom_validator],
                verbose_name="Описание",
            ),
        ),
    ]
